# DO NOT EDIT THIS FILE!
#
# Python module FingerVision generated by omniidl

import omniORB
omniORB.updateModule("FingerVision")

# ** 1. Stub files contributing to this module
import FingerVision_idl

# ** 2. Sub-modules

# ** 3. End
